# This is a build configuration for Javascript (Node.js).
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:8-alpine

pipelines:
  default:
    - step:
       caches:
        - node
       script: # Modify the commands below to build your repository.
         - npm install --quiet
#         - npm outdated
         - CI="" npm run build # https://github.com/facebookincubator/create-react-app/issues/1150