import faq from '../utils/language/faq';

const initialState = {
	languages: {
		en: {
			anon: 'Crypto Anon',
			background_pos_x: '4',
			background_pos_y: '12',
			landing_page_top_menu_home: 'home',
			landing_page_top_menu_news: 'news',
			landing_page_top_menu_support: 'support',
			landing_page_top_menu_login: 'login',
			landing_page_top_menu_register: 'register',
			// 'landing_page_main_title': 'JetCrypto Wallet (JCW) The most friendly crypto wallet in the world',
			landing_page_main_title: 'The most friendly crypto wallet in the world',
			landing_page_main_subtitle:
				'We are happy to help, advice and teach you how to buy and use Bitcoin, Ethereum, Dash, Ripple, Litecoin, Tether, USD Coin.',
			landing_page_know_more_btn: 'Know more',
			jetcrypto_functions_1: 'An easy-to-use management tool of all your cryptocurrency accounts',
			jetcrypto_functions_2:
				'Exchange of BTC, ETH, LTC, XRP, DASH, USDT, USDC, BNB, BCH and replenish from external wallets',
			jetcrypto_functions_3: 'Interest on remaining balance',
			jetiks_description: 'Hi, I am Jetix, your personal\u00a0assistant',
			jetiks_functions_title: 'New best friend',
			jetiks_function_1: 'Tell about the work process',
			jetiks_function_2: 'Explain all the functions of the service',
			jetiks_function_3: 'Prevent you from mistakes',
			jetiks_function_4: 'Offer the right solutions',
			jetiks_function_5: 'Not disturb you when you don’t want it',
			coming_soon: '* coming soon',
			why_jcw_title: 'Why JetCrypto Wallet',
			why_jcw_subtitle: 'the best market expertise',
			reason_1:
				'The JetCrypto team has developed and provide services for a large number of payment and banking systems.',
			reason_2: 'We have 16 years experience in Fintech.',
			reason_3:
				'Our banking experience allows us to gain a deep understanding of UIX when working with remote financial services',
			interface_title: 'Simple and functional JCW interface',
			interface_description:
				'JCW is simple enough to use. Even rookie to cryptocurrency will be able to learn fast how to use it, while ensuring maximum security for one’s coins.',
			jcw_features_title: 'JCW features',
			jcw_features_subtitle: 'Wide range of crypto wallet functions',
			jcw_feature_1: 'Deposit to JCW from another crypto wallet',
			jcw_feature_2: 'Transfer between JCW cryptocurrency accounts',
			jcw_feature_3: 'Three factor authentication',
			jcw_feature_4: 'Mobile top-up with cryptocurrency',
			jcw_feature_5: 'Withdraw from JCW to another crypto wallet',
			jcw_feature_6: 'Exchange between BTC, ETH, LTC, XRP, DASH, USDT, USDC, BNB, BCH',
			jcw_feature_7: 'Offline cold storage',
			jcw_feature_8: 'Web browser version, iOS/Android',
			register_title: 'Start your crypto journey',
			register_subtitle: 'Simple and full functional cryptocurrency wallet',
			reg_phone_notice: 'Please use the phone number capable of receiving SMS messages',
			reg_type_phone_text: 'By phone',
			// 'reg_type_login_text': 'By login',
			reg_type_login_text: 'By E-mail',
			phone_number_placeholder: 'phone number',
			phone_number_or_login_placeholder: 'phone number or login',
			reg_login_placeholder: 'E-mail',
			password_placeholder: 'Password',
			reg_phone_error: 'The length of the string must be 11 characters',
			reg_invitation_placeholder: 'Invitation Code',
			reg_invitation_error_text:
				'Required field. The code must be 10 characters in length and contain only letters and numbers in Latin',
			reg_invitation_error_text_wrong: 'Wrong Invitation code.',
			required_field_error: 'this field is required',
			registration_success_message_title: 'Registration was successful!',
			registration_success_message_description:
				'A message with password was sent to your mobile phone. Enter your phone number and the password from the message to log in',
			change_password_success_message_title: 'Your password was successfully\u00a0changed',
			restore_password_title: 'Password change confirmation',
			restore_password_description:
				'A message with confirmation code was sent to your mobile phone. Enter the confirmation code from the message below to finish the password restoration',
			confirmation_code_placeholder: 'enter the confirmation code',
			new_password_placeholder: 'enter the new password',
			new_password_repeat_placeholder: 'repeat the new password',
			confirmation_code_error_text: 'You must enter the confirmation code',
			new_password_length_error: 'New password must contain at least 6 characters',
			first_pass_field_is_empty: 'Enter your new password',
			second_pass_field_is_empty: 'Confirm your new password',
			passwords_should_be_equal: 'Passwords should be equal',
			restore_text: 'Forgot your password ? You can',
			restore_link_text: 'restore it',
			login_btn_text: 'login',
			register_btn_text: 'register',
			restore_btn_text: 'restore',
			restore_popup_title: 'Restore password',
			ok_btn: 'Ok',
			submit_btn: 'Submit',
			cancel_btn: 'Cancel',
			logout_btn: 'Logout',
			convert_btn: 'Convert',
			register_active_btn_text: 'Register',
			terms_and_privacy_policy:
				'Please read the "Terms and Conditions", "Privacy Policy" carefully and accept them. Open',
			terms_and_conditions: 'Terms and Conditions',
			privacy_policy: 'Privacy Policy',
			terms_and_privacy_policy_done: 'I have carefully read and agree to the ',
			browser_doesnt_support_PDF: ['This browser does not support PDFs. Please ', 'download', ' the PDF to view it'],
			download: 'Download',
			andWord: 'and',
			wallets_menu: 'My wallets',
			wallet_deposit: 'Deposit',
			wallet_deposit_by_card: 'Buy with card',
			wallet_withdraw: 'Withdraw',
			payments_menu: 'Payments and transfers',
			support_menu: 'Support',
			faq_menu: 'FAQ',
			exchange_menu: 'Exchange',
			wallets_title: 'Wallets',
			recent_activity_title: 'Recent activity',
			right_menu_wallets_title: 'My wallets',
			right_menu_balance_title: 'You have',
			selected_payments: 'Selected payments',
			city_payments: 'Payments in your city',
			conversion: 'Conversion',
			// 'agreement_text': 'I agree to the payment terms and conditions',
			agreement_text: 'I agree to the payment ',
			sender_text: 'sender',
			receiver_text: 'receiver',
			amount_text: 'amount',
			sender_account_error_text: 'Please choose the sender wallet',
			receiver_account_error_text: 'Please choose the receiver wallet',
			conversion_balance_error_text: 'Not enough wallet balance',
			conversion_amount_error_text: 'Please enter the amount',
			conversion_conditions_error_text: 'You must agree to the payment terms and conditions',
			payment_success_text: 'Payment successful!',
			remove_payment_success_text: 'Payment was successfully removed!',
			remove_payment_text: 'Do you really want to delete this payment template?',
			delete_text: 'delete',
			support_text: 'The support service will help you with any question',
			support_hint: 'You can ask your questions here',
			support_question_placeholder: 'title',
			support_question_button: 'Send question',
			support_question_success_text: 'Your question was sent to the support service!',
			profile_settings_text: 'My profile',
			security_settings_text: 'Security',
			subscriptions_settings_text: 'Subscriptions',
			person_verification_settings: 'Person verification',
			receive_newsletter_emails: 'Receive newsletter emails',
			receive_email_notifications_about_withdrawals: 'Receive email notifications about withdrawals',
			phone_and_email_settings_title: 'Phone and email',
			phone_and_email_settings_description:
				'We need your phone to confirm withdrawals. E-mail to send the data of your account.',
			// For safety purpose your phone number will be hidden.',
			phone_setting_text: 'phone',
			email_setting_text: 'email',
			change_email_text: 'Change e-mail',
			change_email_placeholder: 'enter your e-mail',
			change_email_success_text: 'Your email was successfully changed',
			personal_data_settings_title: 'Personal data',
			personal_data_settings_description: 'You can change your personal data here',
			first_name_setting_text: 'First name',
			second_name_setting_text: 'Last name',
			birth_date_setting_text: 'Birth date',
			country_of_birth: 'Country of birth',
			source_of_funds: 'Source of funds',
			change_personal_data_text: 'Change personal data',
			change_name_placeholder: 'enter your first name',
			change_second_name_placeholder: 'enter your last name',
			change_birth_date_placeholder: 'enter your birth date',
			change_personal_data_success_text: 'Your personal data was successfully changed',
			geolocation_settings_title: 'Home Address',
			geolocation_settings_description: 'You can change your geo data here',
			city_setting_text: 'city',
			country_setting_text: 'country',
			postal_code_text: 'postal code',
			change_geolocation_text: 'Change home address',
			change_city_placeholder: 'enter your city',
			change_country_placeholder: 'enter your country',
			change_postal_code_placeholder: 'enter your postal code',
			change_geo_data_success_text: 'Your geo data was successfully changed',
			empty_data_text: 'Not set',
			password_setting_title: 'Password',
			password_setting_description:
				'Think of a long password of letters and numbers that you will easily remember, and others difficult to guess',
			change_password_text: 'Change password',
			enter_old_password_placeholder: 'enter old password',
			enter_new_password_placeholder: 'enter new password',
			confirm_new_password_placeholder: '...and again (min 6 symbols)',
			change_password_success_text: 'Your password was successfully changed',
			country_phone_code_placeholder: 'Select your country',
			change_source_of_funds: 'Please enter your source of funds',
			phone_setting_title: 'phone',
			phone_setting_description: 'New phone number',
			change_phone_text: 'Change phone',
			enter_old_phone_placeholder: 'enter old phone number',
			enter_new_phone_placeholder: 'enter new phone number',
			change_phone_success_text: 'Your phone number was successfully changed',
			login_setting_title: 'login',
			login_setting_description: 'New login',
			change_login_text: 'Change login',
			enter_old_login_placeholder: 'enter old login',
			enter_new_login_placeholder: 'enter new login',
			change_login_success_text: 'Your login was successfully changed',
			faq: faq.en,
			cookie_popup_text:
				'This website uses cookies to ensure the best possible service. By continuing to browse this site, you agree to the use of cookies. ',
			cookie_popup_link_text: 'More Info',
			cookie_popup_button_text: 'I agree',
			withdraw_title: 'Withdraw',
			withdraw_transfer_to: 'Recipient wallet',
			withdraw_amount: 'Amount',
			withdraw_wallet: 'Wallet',
			withdraw_errors: [
				'This field is required',
				'This field is required',
				'Invalid wallet address',
				'Not enough wallet balance',
			],
			withdraw_to_wallet: 'Withdraw to wallet',
			withdraw_to_wallet_complete_text: 'Withdraw Complete',
			withdraw_to_wallet_failed_text: 'Withdraw failed!',
			withdraw_to_phone_user_not_found: 'Transfer to this phone number is not available yet.',
			withdraw_to_wallet_too_many_attempts:
				'Too many failed attempts to fetch wallet address / phone number. Try again in 15 minutes.',
			loading_crypto_address: 'loading...',
			loading_crypto_address_error: 'An error has occurred, please try again...',
			timeout_error: 'Server error. Please try again later',
			wallet_events_received: 'Received',
			wallet_events_spent: 'Sent',
			wallet_events_older_activity: 'Older activity',
			session_expired: 'Session time expired! Now you will be redirected to the main page!',
			no_transactions_found: 'No transactions found',
			user_settings_subscriptions_apply_btn: 'Apply changes',
			user_settings_subscriptions_changed: 'Your subscriptions list successfully changed!',
			user_settings_subscriptions_change: 'Change subscriptions',
			app_version_reload_text: 'The version of the application is outdated. Please reload the page.',
			app_version_reload_btn_text: 'Reload',
			birthDate: 'birthday date',
			verificationMessage: 'Enter confirmation code from',
			verificationType: ['"Google Authenticator"', 'Email', 'SMS'],
			noActiveOrders: 'You have no active orders',
			//KYC
			kyc_status_title: 'Your status',
			kyc_status: {
				0: 'Please pass KYC',
				1: 'Data not submitted',
				2: 'Data submitted',
				8: 'KYC passed successfully',
				16: 'KYC failed. Please contact the support team.',
				32: 'KYC failed. Please try again',
			},
			kyc_data_provided_on: 'Data provided on',
			kyc_review_data: 'Review data',
			kyc_pass: 'Pass KYC',

			//Conversion
			amount_is_to_small: 'The conversion amount is too low, min amount is - ',

			//Simplex Form
			min_amount_err: ['Minimum fiat amount should be equivalent to', 'and is'],
			max_amount_err: ['Maximum fiat amount should be equivalent to', 'and is'],
			not_null_err: 'Requested amount should be above zero',
			seconds_left: 'The quote is valid for {quoteValidSeconds} seconds',
			pls_refresh: 'Please refresh the quote',
			buy_txt: 'Buy',
			refresh_txt: 'Refresh',
			purchase_complete: 'Purchase Complete',
			purchase_failed: 'Purchase Failed',

			//Verification
			verification_level: {
				0: 'Not registered',
				1: 'Registered',
				2: 'No personal data',
				3: 'Personalized (not verified)',
				4: 'Verified',
				5: 'Verified by Bank',
			},

			google_auth_notice:
				"If you experiencing issues with Google Authenticator, don't forget to check time correction for codes in your Google Authenticator app",
		},

		ru: {
			anon: 'Crypto Anon',
			background_pos_x: '8',
			background_pos_y: '9',
			landing_page_top_menu_home: 'главная',
			landing_page_top_menu_news: 'новости',
			landing_page_top_menu_support: 'поддержка',
			landing_page_top_menu_login: 'вход',
			landing_page_top_menu_register: 'регистрация',
			// 'landing_page_main_title': 'Jet Crypto Wallet (JCW) Самый дружественный в мире криптовалютный кошелек',
			landing_page_main_title: 'Самый дружественный в мире криптовалютный кошелек',
			landing_page_main_subtitle:
				'С удовольствием поможем, научим и поделимся советом о том, как покупать и использовать Bitcoin, Ethereum, Ethereum Classic, Dash, Monero, Ripple, Nem.',
			landing_page_know_more_btn: 'Узнать больше',
			jetcrypto_functions_1: 'Удобный способ управления всеми своими криптовалютными кошельками',
			jetcrypto_functions_2: 'Обмен BTC, ETH, DASH и пополнение с внешних кошельков',
			jetcrypto_functions_3: 'Процент на остаток на счете',
			jetiks_description: 'Привет, я Jetix - твой персональный помощник',
			jetiks_functions_title: 'Новый лучший друг',
			jetiks_function_1: 'Расскажет о процессе работы',
			jetiks_function_2: 'Объяснит все функции сервиса',
			jetiks_function_3: 'Не даст ошибиться при работе',
			jetiks_function_4: 'Предложит верные решения',
			jetiks_function_5: 'Не будет беспокоить Вас когда не следует',
			coming_soon: '* появится в ближайшее время',
			why_jcw_title: 'Почему JCW',
			why_jcw_subtitle: 'самый лучший опыт на рынке',
			reason_1: 'Команда Jet Crypto разработала и обслуживает большое количество платёжных и банковских систем.',
			reason_2: '16 лет опыта работы в Fintech.',
			reason_3:
				'Глубокое понимание пользовательского опыта при работе с системами дистанционного банковского обслуживания.',
			interface_title: 'Простой и функциональный интерфейс JCW',
			interface_description:
				'JCW достаточно прост в использовании. Даже новичок в области криптовалют сможет быстро разобраться, как пользоваться кошельком, будучи уверенным в безопасности своих денег',
			jcw_features_title: 'Возможности JCW',
			jcw_features_subtitle: 'Широкий спектр функций криптокошелька',
			jcw_feature_1: 'Пополнение JCW с другого криптовалютного кошелька',
			jcw_feature_2: 'Переводы между криптокошельками внутри JCW',
			jcw_feature_3: 'Трёхфакторная аутентификация',
			jcw_feature_4: 'Оплата услуг мобильных операторов через JCW',
			jcw_feature_5: 'Перевод с JCW на другой криптовалютный кошелек',
			jcw_feature_6: 'Мультивалютный обмен BTC, ETH, DASH, XRP, XMR, ETC, LTC, XEM',
			jcw_feature_7: 'Холодный кошелек',
			jcw_feature_8: 'Версия для веб-браузеров, iOS/Android (в разработке)',
			register_title: 'Начните использовать криптовалюты, это просто',
			register_subtitle: 'Простой и многофункциональный криптокошелёк',
			reg_phone_notice: 'Пожалуйста, введите номер телефона, на который будет прислано СМС сообщение',
			reg_type_phone_text: 'По телефону',
			// 'reg_type_login_text': 'По логину',
			reg_type_login_text: 'По e-mail',
			phone_number_placeholder: 'номер телефона',
			phone_number_or_login_placeholder: 'номер телефона или логин',
			reg_login_placeholder: 'E-mail',
			password_placeholder: 'Пароль',
			reg_phone_error: 'Длина строки должна быть 11 символов',
			reg_invitation_placeholder: 'Код приглашения',
			reg_invitation_error_text:
				'Поле обязательно для заполнения. Код быть из 10 символов и содержать только латинские буквы и цифры.',
			reg_invitation_error_text_wrong: 'Неправильный код приглашения',
			required_field_error: 'это поле необходимо заполнить',
			registration_success_message_title: 'Регистрация прошла успешно!',
			registration_success_message_description:
				'Вам было отправлено sms-сообщение с паролем. Для входа в личный кабинет введите свой номер телефона и пароль из сообщения',
			change_password_success_message_title: 'Ваш пароль успешно изменён!',
			restore_password_title: 'Подтверждение смены пароля',
			restore_password_description:
				'Вам было отправлено sms-сообщение с кодом подтверждения. Для завершения операции смены пароля введите код из sms',
			confirmation_code_placeholder: 'введите код подтверждения',
			new_password_placeholder: 'введите новый пароль',
			new_password_repeat_placeholder: 'введите новый пароль повторно',
			confirmation_code_error_text: 'Вы должны ввести код подтверждения',
			new_password_length_error: 'Пароль должен содержать минимум 6 знаков',
			restore_text: 'Забыли пароль? Вы можете',
			restore_link_text: 'восстановить его',
			login_btn_text: 'Вход',
			register_btn_text: 'Регистрация',
			restore_btn_text: 'восстановить',
			restore_popup_title: 'Восстановить пароль',
			ok_btn: 'OK',
			submit_btn: 'Подтвердить',
			cancel_btn: 'Отмена',
			logout_btn: 'Выход',
			convert_btn: 'Конвертировать',
			register_active_btn_text: 'Зарегистрироваться',
			terms_and_privacy_policy:
				'Пожалуйста внимательно ознакомьтесь с Правилами и условиями и Политикой конфиденциальности. Открыть ',
			terms_and_conditions: 'Правилами и условиями',
			privacy_policy: 'Политикой конфиденциальности',
			terms_and_privacy_policy_done: 'Я внимательно ознакомился и согласен с ',
			browser_doesnt_support_PDF: [
				'Ваш браузер не поддерживает PDF. Пожалуйста, ',
				'скачайте',
				' файл для его просмотра.',
			],
			download: 'Скачать',
			andWord: 'и',
			wallets_menu: 'Мои кошельки',
			wallet_deposit: 'Пополнить',
			wallet_deposit_by_card: 'Пополнить картой',
			wallet_withdraw: 'Вывести',
			payments_menu: 'Платежи и переводы',
			support_menu: 'Поддержка',
			faq_menu: 'FAQ',
			exchange_menu: 'Биржа',
			wallets_title: 'Кошельки',
			recent_activity_title: 'Последняя активность',
			right_menu_wallets_title: 'Мои кошельки',
			right_menu_balance_title: 'У Вас есть',
			selected_payments: 'Избранные платежи',
			city_payments: 'Платежи в Вашем городе',
			conversion: 'Конвертация',
			// 'agreement_text': 'Я согласен с правилами и условиями проведения платежа',
			agreement_text: 'Я согласен с ',
			sender_text: 'отправитель',
			receiver_text: 'получатель',
			amount_text: 'сумма',
			sender_account_error_text: 'Пожалуйста, выберите кошелек отправителя',
			receiver_account_error_text: 'Пожалуйста, выберите кошелек получателя',
			conversion_balance_error_text: 'Недостаточно средств',
			conversion_amount_error_text: 'Пожалуйста, введите сумму',
			conversion_conditions_error_text: 'Вы должны согласиться с условиями',
			payment_success_text: 'Платёж успешно проведен!',
			remove_payment_success_text: 'Платёж был успешно удален!',
			remove_payment_text: 'Вы действительно хотите удалить этот платёж?',
			delete_text: 'удалить',
			support_text: 'Служба поддержки поможет Вам с любой проблемой',
			support_hint: 'Здесь Вы можете задать вопрос',
			support_question_placeholder: 'тема',
			support_question_button: 'Задать вопрос',
			support_question_success_text: 'Ваш вопрос был отправлен в службу поддержки',
			profile_settings_text: 'Мой профиль',
			security_settings_text: 'Безопасность',
			subscriptions_settings_text: 'Подписки',
			person_verification_settings: 'Верификация личности',
			receive_newsletter_emails: 'Receive newsletter emails',
			receive_email_notifications_about_withdrawals: 'Receive email notifications about withdrawals',
			phone_and_email_settings_title: 'Телефон и e-mail',
			phone_and_email_settings_description:
				'Телефон нужен, чтобы подтверждать операции и настройки счета. На почту приходят выписки, счета и справки.',
			// Номер телефона спрятан для безопасности.',
			phone_setting_text: 'телефон',
			email_setting_text: 'электронная почта',
			change_email_text: 'Изменить почту',
			change_email_placeholder: 'введите электронную почту',
			change_email_success_text: 'Ваша электронная почта успешно изменена',
			personal_data_settings_title: 'Личные данные',
			personal_data_settings_description: 'Здесь Вы можете изменить Ваши личные данные',
			first_name_setting_text: 'Имя',
			second_name_setting_text: 'Фамилия',
			birth_date_setting_text: 'Дата рождения',
			country_of_birth: 'Страна рождения',
			source_of_funds: 'Источник происхождения денег',
			change_personal_data_text: 'Изменить личные данные',
			change_name_placeholder: 'введите имя',
			change_second_name_placeholder: 'введите фамилию',
			change_birth_date_placeholder: 'введите дату рождения',
			change_personal_data_success_text: 'Ваши личные данные успешно изменены',
			geolocation_settings_title: 'Геолокация',
			geolocation_settings_description: 'Здесь Вы можете изменить информацию о Вашем местоположении',
			city_setting_text: 'город',
			country_setting_text: 'страна',
			postal_code_text: 'индекс',
			change_geolocation_text: 'Изменить данные геолокации',
			change_city_placeholder: 'введите город',
			change_country_placeholder: 'введите страну',
			change_postal_code_placeholder: 'введите индекс',
			change_geo_data_success_text: 'Данные о местоположении успешно изменены',
			empty_data_text: 'Не указано',
			password_setting_title: 'Пароль',
			password_setting_description:
				'Это ваш ключ от интернет-банка. Придумайте длинный пароль из букв и цифр, который вам будет легко запомнить, а другим — сложно угадать.',
			change_password_text: 'Изменить пароль',
			enter_old_password_placeholder: 'введите старый пароль',
			enter_new_password_placeholder: 'введите новый пароль (от 6 символов)',
			change_password_success_text: 'Ваш пароль успешно изменён',
			country_phone_code_placeholder: 'Выберите страну',
			change_source_of_funds: 'Укажите источник происхождения денег',
			faq: faq.ru,
			phone_setting_title: 'телефон',
			phone_setting_description: 'Новый номер телефона',
			change_phone_text: 'Изменить телефон',
			enter_old_phone_placeholder: 'введите старый номер телефона',
			enter_new_phone_placeholder: 'введите новый номер телефона',
			change_phone_success_text: 'Ваш номер телефона успешно изменен',
			login_setting_title: 'логин',
			login_setting_description: 'Новый логин',
			change_login_text: 'Изменить логин',
			enter_old_login_placeholder: 'введите старый логин',
			enter_new_login_placeholder: 'введите новый логин',
			change_login_success_text: 'Ваш логин успешно изменён',
			cookie_popup_text:
				'Нажимая на любую ссылку на этой странице Вы соглашаетесь с нашей политикой использования файлов "cookie". ',
			cookie_popup_link_text: 'Подробнее',
			cookie_popup_button_text: 'Принять',
			withdraw_title: 'Перевод',
			withdraw_transfer_to: 'Целевой кошелек',
			withdraw_amount: 'Сумма',
			withdraw_wallet: 'Кошелек',
			withdraw_errors: [
				'Поле обязательно для заполнения',
				'Поле обязательно для заполнения',
				'Некорректный адрес кошелька',
				'Недостаточно средств',
			],
			withdraw_to_wallet: 'Вывести на кошелек',
			withdraw_to_wallet_complete_text: 'Перевод отправлен',
			withdraw_to_wallet_failed_text: 'Перевод не удался',
			withdraw_to_phone_user_not_found: 'Перевод по данному номеру телефона не доступен',
			withdraw_to_wallet_too_many_attempts:
				'Превышено количество попыток проверки адреса и/или номера телефона. Попробуйте снова через 15 минут.',
			loading_crypto_address: 'Данные загружаются...',
			loading_crypto_address_error: 'При загрузке данных возникла ошибка, попробуйте еще раз...',
			timeout_error: 'Возникла проблема при подключении к серверу. Попробуйте еще раз позже.',
			wallet_events_received: 'Получен',
			wallet_events_spent: 'Отправлен',
			wallet_events_older_activity: 'Ранние операции',
			session_expired: 'Время сессии истекло! Сейчас вы будете перенаправлены на главную страницу!',
			no_transactions_found: 'Транзакций не обнаружено',
			user_settings_subscriptions_apply_btn: 'Изменить данные',
			user_settings_subscriptions_changed: 'Подписка была успешно изменена!',
			user_settings_subscriptions_change: 'Изменение подписок',
			app_version_reload_text: 'Версия приложения устарела. Пожалуйста, перезагрузите страницу.',
			app_version_reload_btn_text: 'Перезагрузить',
			birthDate: 'Дата рождения',
			//KYC
			kyc_status_title: 'Ваш статус',
			kyc_status: {
				0: 'Пожалуйста, пройдите верификацию личности',
				1: 'Данные не отправлены',
				2: 'Данные проходят проверку',
				3: 'Верификация пройдена',
				4: 'Ошибка верификации. Попробуйте еще раз.',
				5: 'Ошибка верификации. Свяжитесь со службой поддержки.',
			},
			kyc_data_provided_on: 'Данные были загружены',
			kyc_review_data: 'Просмотр загруженных данных',
			kyc_pass: 'Пройти верификацию',
			//Conversion
			amount_is_to_small: 'Сумма конвертации меньше возможной, установленной биржей! Минимальная сумма - ',
			//Simplex Form
			min_amount_err: ['Минимальная сумма покупки должна быть эквивалентна', 'и составляет'],
			max_amount_err: ['Максимальная сумма покупки должна быть эквивалентна', 'и составляет'],
			seconds_left: 'Курс действителен {quoteValidSeconds} секунд',
			not_null_err: 'Запрашиваемая сумма должна быть больше нуля',
			pls_refresh: 'Пожалуйста обновите курс',
			buy_txt: 'Купить',
			refresh_txt: 'Обновить',
			purchase_complete: 'Покупка завершена',
			purchase_failed: 'Покупка не удалась',

			//Verification
			verification_level: {
				0: 'Не зарегистрирован',
				1: 'Зарегистрирован',
				2: 'Не заполнены данные для верификации',
				3: 'Персональные данные на рассмотрении',
				4: 'Верификация пройдена',
				5: 'Верификация подтверждена банком',
			},
		},
	},

	errors: {
		en: {
			108: 'Wrong Email and(or) Password',
			try_later: 'An error occurred. Please try again later',
			trade_crypto: 'An error occurred. Please check values and try again later',
		},
	},

	activeLanguage: !localStorage.getItem('local_lang') ? 'en' : localStorage.getItem('local_lang'),
};

export default function language(state = initialState, action) {
	switch (action.type) {
		case 'CHANGE_LANGUAGE':
			return {
				...state,
				activeLanguage: action.language === null ? 'en' : action.language,
			};

		default:
			return state;
	}
}
